import Foundation

/// Options controlling how source artwork is turned into an Amiga `.info` file.
///
/// Defaults reflect typical conventions: a compact, few-colour **planar** image
/// for OS1–3 compatibility, plus a 24-bit **GlowIcon** (48×48 artwork centred in
/// a 54×54 canvas) for OS3.5+, with an auto-generated glow on the clicked state.
public struct IconOptions {
    public var type: IconType = .project
    public var defaultTool: String = ""
    public var toolTypes: [String] = []

    // --- Classic planar fallback (always written; OS1–3 era) ---
    /// Palette the planar indices are matched against (the Workbench screen
    /// palette interprets them at display time).
    public var planarPalette: [RGB] = workbench4Palette
    /// Artwork is fit within this, centred in `planarCanvasSize`.
    public var planarContentSize: Int = 36
    /// On-disk planar image dimension. Small, as was typical pre-GlowIcons.
    public var planarCanvasSize: Int = 40

    // --- ColorIcon / GlowIcon (OS3.5+, 24-bit) ---
    public var writeColorIcon: Bool = true
    public var colorContentSize: Int = 48
    public var colorCanvasSize: Int = 54
    public var colorMaxColors: Int = 256
    public var compressColorIcon: Bool = true

    // --- Selected ("clicked") state glow ---
    /// When no explicit selected image is supplied, derive the clicked state by
    /// adding a glow to the normal artwork.
    public var autoGlow: Bool = true
    /// Glow thickness in pixels. Clamped to the canvas margin so it never clips.
    public var glowRadius: Int = 3
    public var glowColor: RGB = RGB(0xFF, 0x8B, 0x00) // warm GlowIcon orange

    // --- NewIcons (experimental; off by default — see NewIcons.swift) ---
    public var writeNewIcons: Bool = false

    public init() {}
}

/// Assembles a complete `.info` file from source artwork.
public enum IconWriter {

    /// Builds the `.info` byte stream.
    ///
    /// - Parameters:
    ///   - normal: the unclicked-state artwork (any size; it is scaled/centred).
    ///   - selected: optional clicked-state artwork. If `nil` and `autoGlow` is
    ///               on, the clicked state is generated by glowing `normal`.
    public static func build(normal: RGBAImage,
                             selected: RGBAImage?,
                             options: IconOptions) throws -> [UInt8] {
        // ---- Planar fallback (small, fixed palette) ---------------------
        let planarNormalRGBA = normal.centered(inCanvas: options.planarCanvasSize,
                                                contentSize: options.planarContentSize)
        let planarNormal = ColorQuantizer.map(planarNormalRGBA, to: options.planarPalette)
        let planarDepth = max(1, Int(ceil(log2(Double(max(2, options.planarPalette.count))))))
        let planarNormalImg = PlanarImage(planarNormal, depth: planarDepth)

        // A planar selected image is only written when the caller supplies one
        // explicitly (classic icons usually rely on colour-complement highlight).
        var planarSelectedImg: PlanarImage?
        if let sel = selected {
            let rgba = sel.centered(inCanvas: options.planarCanvasSize,
                                    contentSize: options.planarContentSize)
            let mapped = ColorQuantizer.map(rgba, to: options.planarPalette)
            planarSelectedImg = PlanarImage(mapped, depth: planarDepth)
        }

        // ---- ColorIcon / GlowIcon --------------------------------------
        var colorIcon: ColorIcon?
        if options.writeColorIcon {
            let normRGBA = normal.centered(inCanvas: options.colorCanvasSize,
                                           contentSize: options.colorContentSize)
            let normIndexed = ColorQuantizer.quantize(normRGBA, maxColors: options.colorMaxColors)

            let selRGBA: RGBAImage?
            if let sel = selected {
                selRGBA = sel.centered(inCanvas: options.colorCanvasSize,
                                       contentSize: options.colorContentSize)
            } else if options.autoGlow {
                // Glow may not exceed the margin, or it would be clipped.
                let margin = (options.colorCanvasSize - options.colorContentSize) / 2
                let radius = max(1, min(options.glowRadius, max(1, margin)))
                selRGBA = normRGBA.addingGlow(radius: radius,
                                              color: (options.glowColor.r, options.glowColor.g, options.glowColor.b))
            } else {
                selRGBA = nil
            }
            let selIndexed = selRGBA.map { ColorQuantizer.quantize($0, maxColors: options.colorMaxColors) }
            colorIcon = ColorIcon(normal: normIndexed, selected: selIndexed,
                                  compress: options.compressColorIcon)
        }

        // ---- Tool types (optionally prefixed with NewIcons data) -------
        var toolTypes = options.toolTypes
        if options.writeNewIcons {
            let normIndexed = ColorQuantizer.quantize(
                normal.centered(inCanvas: options.colorCanvasSize, contentSize: options.colorContentSize),
                maxColors: 256)
            let newIconLines = NewIcons.encode(normal: normIndexed, selected: nil)
            toolTypes = newIconLines + toolTypes
        }

        return try serialize(type: options.type,
                             defaultTool: options.defaultTool,
                             toolTypes: toolTypes,
                             planarNormal: planarNormalImg,
                             planarSelected: planarSelectedImg,
                             colorIcon: colorIcon)
    }

    // MARK: - DiskObject serialisation

    private static func serialize(type: IconType,
                                  defaultTool: String,
                                  toolTypes: [String],
                                  planarNormal: PlanarImage,
                                  planarSelected: PlanarImage?,
                                  colorIcon: ColorIcon?) throws -> [UInt8] {
        var w = BinaryWriter()

        // ---- DiskObject header (78 bytes) ------------------------------
        w.u16(0xE310)                       // do_Magic  (WB_DISKMAGIC)
        w.u16(1)                            // do_Version (WB_DISKVERSION)

        // struct Gadget (44 bytes)
        w.u32(0)                            // ga_NextGadget
        w.i16(0)                            // ga_LeftEdge
        w.i16(0)                            // ga_TopEdge
        w.i16(Int16(planarNormal.width))    // ga_Width
        w.i16(Int16(planarNormal.height))   // ga_Height
        // Flags: GFLG_GADGIMAGE (0x0004); + GFLG_GADGHIMAGE (0x0002) when there
        // is a second image, else GFLG_GADGHCOMP (0x0000) colour-complement.
        let flags: UInt16 = planarSelected != nil ? 0x0006 : 0x0004
        w.u16(flags)                        // ga_Flags
        w.u16(0x0003)                       // ga_Activation (RELVERIFY|GADGIMMEDIATE)
        w.u16(0x0001)                       // ga_GadgetType (BOOLGADGET)
        w.u32(1)                            // ga_GadgetRender (non-NULL: image follows)
        w.u32(planarSelected != nil ? 1 : 0)// ga_SelectRender
        w.u32(0)                            // ga_GadgetText
        w.i32(0)                            // ga_MutualExclude
        w.u32(0)                            // ga_SpecialInfo
        w.u16(0)                            // ga_GadgetID
        w.u32(0)                            // ga_UserData

        w.u8(type.rawValue)                 // do_Type
        w.u8(0)                             // padding

        let hasDefaultTool = !defaultTool.isEmpty
        let hasToolTypes = !toolTypes.isEmpty
        w.u32(hasDefaultTool ? 1 : 0)       // do_DefaultTool
        w.u32(hasToolTypes ? 1 : 0)         // do_ToolTypes
        w.i32(0)                            // do_CurrentX (NO_ICON_POSITION would be 0x80000000)
        w.i32(0)                            // do_CurrentY
        w.u32(0)                            // do_DrawerData (none)
        w.u32(0)                            // do_ToolWindow
        w.i32(0)                            // do_StackSize

        // ---- Images ----------------------------------------------------
        planarNormal.write(into: &w)
        planarSelected?.write(into: &w)

        // ---- DefaultTool string ----------------------------------------
        if hasDefaultTool { writeString(defaultTool, into: &w) }

        // ---- ToolTypes -------------------------------------------------
        if hasToolTypes {
            // do_ToolTypes is an array of (count + 1) pointers on disk: a 32-bit
            // count field equal to (n + 1) * 4, then each string as a sized blob.
            w.u32(UInt32((toolTypes.count + 1) * 4))
            for tt in toolTypes { writeString(tt, into: &w) }
        }

        // ---- Trailing ColorIcon (GlowIcon) FORM ------------------------
        if let colorIcon { w.bytes(try colorIcon.encode()) }

        return w.data
    }

    /// Writes an Amiga sized string: 32-bit length (including NUL), bytes, NUL.
    private static func writeString(_ s: String, into w: inout BinaryWriter) {
        // Amiga icons are Latin-1; map non-ASCII conservatively.
        let bytes = s.unicodeScalars.map { UInt8($0.value <= 0xFF ? $0.value : 0x3F) }
        w.u32(UInt32(bytes.count + 1))
        w.bytes(bytes)
        w.u8(0)
    }
}
